apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iseyhuslb-python 
  janus-idp.io/tekton: iseyhuslb-python
  backstage.io/kubernetes-id: iseyhuslb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iseyhuslb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml